/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.Pessoa;
import java.util.ArrayList;

/**
 *
 * @author rcabral
 */
public class Listagem extends javax.swing.JFrame {

    private ArrayList<Pessoa> listaDePessoa = new ArrayList();
    
    
    /**
     * Creates new form Listagem
     */
    public Listagem() {
        initComponents();
    }
    
    public void ListaPessoa(){
        TextListaPessoa.setText("");
        for (int i = 0; i < getListaDePessoa().size(); i++) {
            TextListaPessoa.setText(TextListaPessoa.getText() +
                    i + " " + getListaDePessoa().get(i).MostrarDados() + "\n");
            
        }
    }
    
    public void cadastrarPessoa(Pessoa pessoa){
        getListaDePessoa().add(pessoa);
    }

    public void AtualizarPessoa(int id, String novoNome, int novaIdade, String novoCPF){
        
                getListaDePessoa().get(id).setNome(novoNome);
                getListaDePessoa().get(id).setIdade(novaIdade);
                getListaDePessoa().get(id).setCpf(novoCPF);
            }
            
        
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ButoCadastro = new javax.swing.JButton();
        ButoAlterar = new javax.swing.JButton();
        ButoDeletar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextListaPessoa = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        TextIdDelete = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tela de Listagem :(");

        ButoCadastro.setText("Cadastrar");
        ButoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButoCadastroActionPerformed(evt);
            }
        });

        ButoAlterar.setText("Alterar");
        ButoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButoAlterarActionPerformed(evt);
            }
        });

        ButoDeletar.setText("Deletar");
        ButoDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButoDeletarActionPerformed(evt);
            }
        });

        TextListaPessoa.setColumns(20);
        TextListaPessoa.setRows(5);
        jScrollPane1.setViewportView(TextListaPessoa);

        jLabel2.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButoCadastro)
                        .addGap(40, 40, 40)
                        .addComponent(ButoAlterar)
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButoDeletar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextIdDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextIdDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButoCadastro)
                    .addComponent(ButoAlterar)
                    .addComponent(ButoDeletar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButoCadastroActionPerformed
        // TODO add your handling code here:
        Cadastro telaCad = new Cadastro(this);
        telaCad.setVisible(true);
        
        setVisible(false);
    }//GEN-LAST:event_ButoCadastroActionPerformed

    private void ButoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButoAlterarActionPerformed
        // TODO add your handling code here:
        Atualizar telaAtu = new Atualizar(this);
        telaAtu.setVisible(true);
        
        setVisible(false);
    }//GEN-LAST:event_ButoAlterarActionPerformed

    private void ButoDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButoDeletarActionPerformed
        // TODO add your handling code here:
        listaDePessoa.remove(Integer.parseInt(TextIdDelete.getText()));
        
        ListaPessoa();
    }//GEN-LAST:event_ButoDeletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButoAlterar;
    private javax.swing.JButton ButoCadastro;
    private javax.swing.JButton ButoDeletar;
    private javax.swing.JTextField TextIdDelete;
    private javax.swing.JTextArea TextListaPessoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the listaDePessoa
     */
    public ArrayList<Pessoa> getListaDePessoa() {
        return listaDePessoa;
    }

    /**
     * @param listaDePessoa the listaDePessoa to set
     */
    public void setListaDePessoa(ArrayList<Pessoa> listaDePessoa) {
        this.listaDePessoa = listaDePessoa;
    }

    String getText() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
